name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd Backend
          npm install 

      - name: Run tests
        run: |
          cd Backend
          npm test

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend Docker image
        run: |
          docker build -t backend_latest -f Backend/Dockerfile .

      - name: Tag Docker image for backend
        run: docker tag backend_latest username/backend_latest
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Push Backend Docker image
        run: |
          docker push username/backend_latest

  frontend:
    name: Frontend CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd Frontend
          npm install

      - name: Run tests
        run: |
          cd Frontend
          npm test -- --ci --silent

      - name: Build application
        run: |
          cd Frontend
          npm run build

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Frontend Docker image
        run: |
          docker build -t frontend_latest -f Frontend/Dockerfile .

      - name: Tag Docker image for frontend
        run: docker tag frontend_latest username/frontend_latest    

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Push Frontend Docker image
        run: |
          docker push username/frontend_latest
